### ISSUE TITLE
Avaliação de Codigo.

### ISSUE THREAD

**Issue by cesarionto** [luancad/turingTestLuanDesenvolvedor#1]
Eai luan, parabens pelo seu código.
Tenho apenas uma colocação pra colocar, e espero que acate e melhore seu codigo.
Percebi que usou a classe Agenda para ser o seu modelo, entendo que a sua api tratava-se de uma agenda, entretanto, a classe não mostra o que de fato o objeto é, acredito que deveria se chamar "Contato". No mais, esta tudo certo.

Aproveite o tempo que falta para dar um refactor no seu codigo.

**Comment by luancad** [comment]
Feito!
